# Generated by Django 4.1.6 on 2023-03-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employeee',
        ),
    ]
